### ISSUE TITLE
Dont load and cant uninstall

### ISSUE THREAD

**Issue by edlvox** [buxared/BananaMangaReader#1]
Hi, i tried BMR on a Libra 2 but it just loads a blank screen and MagaKakalot link reboots the device.

Tried to uninstall but is a no go too.

**Comment by buxared** [comment]
That's interesting. Was NickelMenu installed correctly? The mangakakalot link just opens the browser and navigates to the url. That should have worked even if there is an issue with BMR.  Can you try adding the following line to the nickelmenu config file?

menu_item :main    :Sudoku        :nickel_extras      :sudoku


This should open the inbuilt sudoku game. Try and see if this works

**Comment by edlvox** [comment]
Yes, i have Nickelmenu working with a few shortcuts already, I did reset the Kobo, will try to reinstall and see how it goes...

**Comment by edlvox** [comment]
Almost same result, the link worked now, it opens the page (so something was wrong before, BMR never opens, just a blank screen.

The uninstall file didnt work did several attempts, including after clean reboots, manually deleting doesnt work as it complains that several files from /bmrpyenv/lib/python3.10 are in use, this after several reboots too.

**Comment by buxared** [comment]
Great, so NickelMenu is working. If the files are in use, then maybe the BMR server (python code) is running in the background. Don't press the "Start BMR server" button again. This will start multiple instances of the server.

Can you try manually opening the browser (More>Beta Features>Web browser (press start)) and navigating to either http://banana:1234/ or http://0.0.0.0:1234/ or http://127.0.0.42:1234/
this should take you to the right webpage.
If this works, use the menu button in the webpage to go to "close app" and press the shut down button. This will kill all of the python processes. Hopefully the regular way of opening BMR will work in your next attempt after this.

----------------------------------------------------------------------------------------------------------------------------------------
If this does not work, we should try to telnet into your kobo and kill the processes related to BMR.
Adding the following lines into the nickelmenu config file will give you the telnet button

menu_item :main    :Telnet (toggle)    :cmd_output         :500:quiet :/usr/bin/pkill -f "^/usr/bin/tcpsvd -E 0.0.0.0 2023"
     chain_success:skip:5
       chain_failure                      :cmd_spawn          :quiet :/bin/mount -t devpts | /bin/grep -q /dev/pts || { /bin/mkdir -p /dev/pts && /bin/mount -t devpts devpts /dev/pts; }
       chain_success                      :cmd_spawn          :quiet :exec /usr/bin/tcpsvd -E 0.0.0.0 2023 /usr/sbin/telnetd -i -l /bin/login
       chain_success                      :dbg_toast          :Started Telnet server on port 2023
       chain_failure                      :dbg_toast          :Error starting Telnet server on port 2023
       chain_always:skip:-1
     chain_success                        :dbg_toast          :Stopped Telnet server on port 2023

We will also need the ip address of your kobo. There's another line you need to add to the nickelmenu config file for this:

menu_item :main    :IP Address         :cmd_output         :500:/sbin/ifconfig | /usr/bin/awk '/inet addr/{print substr($2,6)}'


Next, on your computer, you will have to install an ssh client like putty (https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html)

Then, on your kobo (make sure you are connected to wifi), check the ip address by clicking "IP Address" in the nickelmenu.
Then start Telnet by clicking "Telnet (toggle)" in the nickelmenu.

Next, open Putty on your computer.
Enter the ip address you found and 2023 in the port
select telnet under connection type, and then click open at the bottom.

This opens a terminal in your kobo. You can now log in and interact with it.
In the window that opens, enter type in `root` as the kobo login. 
(you have to click on the wifi button at the top of your kobo screen to make sure wifi stays connected during the following steps)

In the putty terminal window, type `ps` and hit enter. This will list all the running processes. one or more of them might be related to BMR.

To kill these processes, type in the command: `pkill -9 -f "BMR"` or  `pkill -9 -f "bmr"`

run `ps` again to make sure that the bmr processes have disappeared.

you can log out by typing the command `exit`

---------------------------------------------------------------------------------------------------------------------------------------
I'm sad that BMR didn't work on your device. 
I hope this helps. You should at least be able to manually delete the application.
Let me know how it goes.
